### ISSUE TITLE
баг в функции сравнения

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#101]
https://github.com/kavladst/grobner-basis/blob/186ea2833a3c78539c26e864cb51542dd3275000/MonomialOrder.h#L50
Что это за хрень тут написана?
Вы понимаете, что тут написана тождественная истина?
(если mon1 < mon2 верно, то mon2 < mon1 неверно) и (если mon1< mon2 не верно, то mon2 < mon1 верно)
Далее, дурацкое имя func. Если вы бежите по контейнеру с именем comparators, то очевидно, что его элемент -- это comparator
for (const auto& comparator : comparators_) {
if (comparator(mon1, mon2)
return true;
if (compartor(mon2, mon1)
return false;
}
return false;

**Comment by kavladst** [comment]
func исправил
Но ваше первое утверждение неверно
Если mon1 = mon2, то mon1 < mon2 неверно и mon2 < mon1 тоже неверно

**Comment by DimaTrushin** [comment]
Согласен, это я облажался, не правильно прочел условие. Это хорошо, что вы такое проверяете. Тем не менее у меня есть два аргумента против такого кода:
1) Я не смог его правильно прочитать. Я если честно, три раза переписывал свой комментарий к этому куску кода. Я понимал, что вы хотите поверить условие, равны ли части с переменными или нет. Но так и не смог этого увидеть. 
Проблема в том, что вы это сделали в очень неожиданной форме (отсюда мой первый комментарий про то, что это хрень. Это моя реакция при первом прочтении, когда я вообще не понял, что вы тут проверяете). Канонический способ  проверки такой, вы хотие проверить
x != y
это выполнено тогда и только тогда
x < y или y < x
То есть
if (cmparator(mon1, mon2) || comparator(mon2, mon1))
2) Ваш способ не эффективный. Для вычисления результата операторов == и != нужно обязательно знать значения и левой и право части. Когда вы пишите код вида
cmparator(mon1, mon2) || comparator(mon2, mon1)
вы получаете тот же самый результат, но оператор || вычисляется лениво. Если левая часть от него будет истина, правая часть вычисляться не будет. Статистически (при большом количестве вызовов такого выражения) в половине случаев у вас не будет вызываться второе сравнение.

Предложенный мною код эквиваентен тому, что я написал выше, но только разнесен в несколько строчек. Кроме того, в предложенном в предыдущем комментари варианте отсутствует повторный вызов comparator(mon1, mon2) внутри блока if. Что может гипотетически сэкономить еще один вызов (гипотетически, потому что может быть компиляторы умеют оптимизировать подобные вызовы, когда видят условия в if и внутри него, но я не специалист в компиляторах, это надо проверять на godbolt).

В сухом остатке. Я бы предложил все равно изменить этот кусок на
if(cmparator(mon1, mon2) || comparator(mon2, mon1)) 
или на предложенный ране из соображений читаемости и производительности.
