### ISSUE TITLE
очень хорошо сделано

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#124]
https://github.com/kavladst/grobner-basis/blob/b0b8d454944ca959831008e0daee4765c6554f75/MonomialOrder.h#L61

Очень правильно и красиво все реализовано. Подумал, что так как я пишу только замечания, может сложиться впечатление, что я вечно всем не доволен. Потому решил выразить положительные эмоции от увиденного.

**Comment by kavladst** [comment]
:)
