### ISSUE TITLE
5 вложенных циклов

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#134]
https://github.com/kavladst/grobner-basis/blob/5e9bb50ca461d62b48346c34b87d7095824aec9f/Algorithm.h#L52

Нужен рефакторинг.
 - Во-первых, я заметил, что когда я говорю, что надо вставить некоторый код, вы напрямую вставляете 20 строчек кода туда, куда я просил. Я же со своей стороны в таком случае подразумеваю всегда, что вы напишете отдельный метод и в указанном месте вызовете его.
 - Во-вторых, посмотрите на количество вложенных циклов. Цикл сам по себе -- это уже не очень хорошо. Два вложенных цикла надо стараться избегать как только возможно. Никогда ни при каких условиях не допускать трех вложенных циклов. А у вас аж пять вложенных циклов!

Короче. Все алгоритмы надо отрефакторить так, чтобы было НЕ более 2 вложенных циклов.

Почему это надо. Чтобы понять как работает код с циклом читающему приходится:
1) понять, что делает тело цикла
2) понять стартовые условия цикла
3) понять инварианты цикла
4) понять условия выхода из цикла
5) понять какие внешние переменные для цикла модифицируются.
А теперь представьте, что в теле цикла есть еще цикл. Это значит в каждом пункте у меня идет рекурсивная процедука с таким же списком пунктов. Невозможно читать, поддерживать и анализировать программу с тремя вложенными циклами, а уж тем более с пятью.

**Comment by kavladst** [comment]
5 циклов убрал
В reduction оставил 3 цикла, по-моему это правильный вариант

**Comment by DimaTrushin** [comment]
> В reduction оставил 3 цикла, по-моему это правильный вариант

Сделать так, чтобы было НЕ более двух вложенных циклов.
