### ISSUE TITLE
move не сработает из-за неверной сигнатуры конструктора

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#138]
https://github.com/kavladst/grobner-basis/blob/306e5424a099cfd1f82d948ce986f0b10c2c0a2e/Algorithm.h#L8
std::move НЕ делает move. Это лишь cast. Про это надо слушать тут https://youtu.be/IqVZG6jWXvs
Чтобы move сработал надо, чтобы параметр был как минимум не константным, а чтобы ничего не сломать, он должен передаваться by value. Я уже писал о том, что правильная сигнатура конструктора -- конструктор принимает свои аргументы by value! Это касается всех конструкторов! Правильная сигнатура
Algorithm(MonomialOrder<T, TNumberOfVariables> order)
copy elision сделает тут свою работу. Я же вам специально подборку статей кинул про copy elision в плюсах с подробными примерами как это работает.

**Comment by UnholyDk** [comment]
С Английским все плохо :(

**Comment by DimaTrushin** [comment]
Я понял, тогда надо чтобы я вам это рассказал на русском. Или мне надо будет найти русскоязычные источники. Надо было про это раньше сказать. Я просто не знал. Вообще, стоит всегда предупреждать своего руководителя обо всем. Запомните, хуже будет только в том случае, когда вы постесняетесь о чем-то предупредить.
