### ISSUE TITLE
предложение/вопрос

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#49]
https://github.com/kavladst/grobner-basis/blob/a71405a2a7b125ef5b27fc1691d82f08b7898323/MonomialOrder.h#L31
Может быть стоит добавить 
bool operator() (const Monomial< T>&, const Monomial< T>&)
для совместимости с алгоритмами STL?
Другое дело, что это не полный порядок и у вас копирование объектов типа MonomialOrder вообще говоря дорогое, так как надо копировать контейнер.

**Comment by kavladst** [comment]
Для это и сделал сравнение мономов в объекте типа MonomialOrder
