### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#52]
https://github.com/kavladst/grobner-basis/blob/a71405a2a7b125ef5b27fc1691d82f08b7898323/Polynomial.h#L10
Вы храните мономы в векторе. При этом подразумевается какая-нибудь сортировка мономов или они идут как попало?

**Comment by kavladst** [comment]
Идут как попало. Сортируются они уже с помощью класса PolynomialOreder, так как они могут быть отсортированы по разным правилам.
