### ISSUE TITLE
небезопасный метод

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#69]
https://github.com/kavladst/grobner-basis/blob/a71405a2a7b125ef5b27fc1691d82f08b7898323/PolynomialSet.h#L21
Небозопасный метод в публичном интерфейсе! Нужен ли он вам!?
Скорее всего вы захотите отсортировать множество полиномов и обращаться к элементам по возрастанию или убыванию. Но тогда это должны быть методы из Algorithms

**Comment by kavladst** [comment]
Индексы полиномам нужны лишь для их отличия

**Comment by DimaTrushin** [comment]
Я понял, просто у вас на самом деле не set (причем НЕ математический set и НЕ программистский set), а вектор и вы хотите этим пользоваться. Тогда, видимо, стоит так и назвать PolynomialVector ваш класс. Тогда это будет хотя бы ожидаемо.
