### ISSUE TITLE
кривой конструктор

### ISSUE THREAD

**Issue by DimaTrushin** [kavladst/grobner-basis#83]
https://github.com/kavladst/grobner-basis/blob/186ea2833a3c78539c26e864cb51542dd3275000/Monomial.h#L22
- Во-первых, ссылка на передаваемый контейнер degree намекает, что вы будете менять данные, что не правда. Должна быть const ссылка.
- Во-вторых, плохо задавать объект данными зависящими от имплементации. Лучше уж сделать конструктор от variadic template или от initializer_list, что очень геморройно, но можно заставить работать 
https://stackoverflow.com/questions/5549524/how-do-i-initialize-a-member-array-with-an-initializer-list
или
https://stackoverflow.com/questions/6893700/how-to-construct-stdarray-object-with-initializer-list
- В-третьих, вы делаете лишнюю работу в теле конструктора. У вас теперь все контейнеры одной длины! Потому вам не надо делать проверку границ массива, кроме того, можно просто написать:
degrees_ = degrees;
- В-четвертых, если у вас степени задаются знаковым типом int, то тут вы допускаете. что class invariant "неотрицательные степени" не выполняется!

**Comment by kavladst** [comment]
Долго думали, не смогли понять в чем проблема во втором пункте :( Другое исправили

**Comment by DimaTrushin** [comment]
Второе плохо тем, что вы в будущем захотите исправить std::array на что-то другое, может быть вообще на обычный c array или еще какую структуру данных (мало ли). тогда этот конструктор сломает код пользователя. Он будет создавать array, а ваш новый класс не принимает array. Лучше использовать initializer_list. Одно из преимущест initializer_list -- он легко копируемый и его можно передавать by value в конструкторе не беспокоясь о долгом копировании.
Кроме того, вы будете писать что-то вроде
Monomial <Rational, 3> m1( 4, {0,0,1});
чтобы задать моном с коэффициентом 4 и степенями переменных 0, 0, 1.
Такой код будет компилироваться всегда, даже если вы поменяете реализацию вашего класса. А минусов в реализации нет, так как array  инициализируется по initializer_list без проблем.
